name: towservice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.1.0
  get: ^4.7.2
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  intl:
  device_preview: ^1.2.0
  bottom_picker: ^3.2.1
  pinput: ^5.0.1
  persistent_bottom_nav_bar: ^6.2.1
  google_maps_flutter: ^2.6.1
  permission_handler:
  chat_bubbles:
  flutter_polygon:
  flutter_rating_bar: ^4.0.1
  url_launcher:
  location:
  geocoding:
  location_picker_text_field:
  dotted_border: ^2.1.0
  mime_type: ^1.0.1
  socket_io_client: ^3.1.2
  lottie:
  flutter_widget_from_html:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/global/custom_assets/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

#  dart run build_runner build

  fonts:
    - family: Csaction
      fonts:
        - asset: assets/fonts/csaction-regular.otf

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
