name: towservice
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.1.0
  get: ^4.7.2
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  device_preview: ^1.3.1
  bottom_picker: ^3.2.1
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/global/custom_assets/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true

  fonts:
    - family: Csaction
      fonts:
        - asset: assets/fonts/csaction-regular.otf

  assets:
    - assets/images/
    - assets/icons/
